{"content": {"suites": {"0": {"status": {"total_pass": 2, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 6, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_1_SetupOs", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_2_Login", "rerun": "0"}, "2": {"status": "FAIL", "message": "   selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\".el-sub-menu__title > #pembinaan-10\"}\n     (Session info: chrome=112.0.5615.137)\n   Stacktrace:\n   0   chromedriver                        0x0000000102cebae8 chromedriver + 4958952\n   1   chromedriver                        0x0000000102ce37b3 chromedriver + 4925363\n   2   chromedriver                        0x00000001028a51d6 chromedriver + 475606\n   3   chromedriver                        0x00000001028e8a20 chromedriver + 752160\n   4   chromedriver                        0x00000001028e8c81 chromedriver + 752769\n   5   chromedriver                        0x000000010292cf64 chromedriver + 1032036\n   6   chromedriver                        0x000000010290ec3d chromedriver + 908349\n   7   chromedriver                        0x000000010292a25b chromedriver + 1020507\n   8   chromedriver                        0x000000010290e9e3 chromedriver + 907747\n   9   chromedriver                        0x00000001028d8aef chromedriver + 686831\n   10  chromedriver                        0x00000001028da00e chromedriver + 692238\n   11  chromedriver                        0x0000000102ca79ad chromedriver + 4680109\n   12  chromedriver                        0x0000000102cacc12 chromedriver + 4701202\n   13  chromedriver                        0x0000000102cb379f chromedriver + 4728735\n   14  chromedriver                        0x0000000102cadb7a chromedriver + 4705146\n   15  chromedriver                        0x0000000102c8027e chromedriver + 4518526\n   16  chromedriver                        0x0000000102ccd908 chromedriver + 4835592\n   17  chromedriver                        0x0000000102ccda87 chromedriver + 4835975\n   18  chromedriver                        0x0000000102cdd00f chromedriver + 4898831\n   19  libsystem_pthread.dylib             0x00007ff80f4a71d3 _pthread_start + 125\n   20  libsystem_pthread.dylib             0x00007ff80f4a2bd3 thread_start + 15\n", "test_name": "test_3_AksesMenu", "rerun": "0"}, "3": {"status": "FAIL", "message": "   selenium.common.exceptions.TimeoutException: Message: \n   Stacktrace:\n   0   chromedriver                        0x0000000102cebae8 chromedriver + 4958952\n   1   chromedriver                        0x0000000102ce37b3 chromedriver + 4925363\n   2   chromedriver                        0x00000001028a51d6 chromedriver + 475606\n   3   chromedriver                        0x00000001028e8a20 chromedriver + 752160\n   4   chromedriver                        0x00000001028e8c81 chromedriver + 752769\n   5   chromedriver                        0x000000010292cf64 chromedriver + 1032036\n   6   chromedriver                        0x000000010290ec3d chromedriver + 908349\n   7   chromedriver                        0x000000010292a25b chromedriver + 1020507\n   8   chromedriver                        0x000000010290e9e3 chromedriver + 907747\n   9   chromedriver                        0x00000001028d8aef chromedriver + 686831\n   10  chromedriver                        0x00000001028da00e chromedriver + 692238\n   11  chromedriver                        0x0000000102ca79ad chromedriver + 4680109\n   12  chromedriver                        0x0000000102cacc12 chromedriver + 4701202\n   13  chromedriver                        0x0000000102cb379f chromedriver + 4728735\n   14  chromedriver                        0x0000000102cadb7a chromedriver + 4705146\n   15  chromedriver                        0x0000000102c8027e chromedriver + 4518526\n   16  chromedriver                        0x0000000102ccd908 chromedriver + 4835592\n   17  chromedriver                        0x0000000102ccda87 chromedriver + 4835975\n   18  chromedriver                        0x0000000102cdd00f chromedriver + 4898831\n   19  libsystem_pthread.dylib             0x00007ff80f4a71d3 _pthread_start + 125\n   20  libsystem_pthread.dylib             0x00007ff80f4a2bd3 thread_start + 15\n       assert False\n", "test_name": "test_4_ClickButtonTambah", "rerun": "0"}, "4": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x15aad3f70>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=56274): Max retries exceeded with url: /session/fb6ce501212e5604fba5403207c096d9/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15aad3f70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_5_InputBidangGiatja", "rerun": "0"}, "5": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x15cd29c10>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=56274): Max retries exceeded with url: /session/fb6ce501212e5604fba5403207c096d9/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15cd29c10>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_18_InputGambar", "rerun": "0"}, "6": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x15cb8c520>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=56274): Max retries exceeded with url: /session/fb6ce501212e5604fba5403207c096d9/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15cb8c520>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_19_Keterangan", "rerun": "0"}, "7": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x15aa9ec40>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=56274): Max retries exceeded with url: /session/fb6ce501212e5604fba5403207c096d9/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15aa9ec40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_32_exit", "rerun": "0"}}, "suite_name": "1.KegiatanKerja/Fungsional/test_GiatjaTambah.py"}}}, "date": "May 03, 2023", "start_time": 1683078398.215595, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "2", "fail": "6", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "8"}