{"content": {"suites": {"0": {"status": {"total_pass": 18, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 7, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_1_SetupOs", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_2_Login", "rerun": "0"}, "2": {"status": "PASS", "message": "", "test_name": "test_2_AksesMenu", "rerun": "0"}, "3": {"status": "PASS", "message": "", "test_name": "test_3_CreateButton", "rerun": "0"}, "4": {"status": "PASS", "message": "", "test_name": "test_4_InputLuasUpt", "rerun": "0"}, "5": {"status": "PASS", "message": "", "test_name": "test_5_InputKapasitasHunian", "rerun": "0"}, "6": {"status": "PASS", "message": "", "test_name": "test_6_InputLuasBlok", "rerun": "0"}, "7": {"status": "PASS", "message": "", "test_name": "test_7_InputJumlahPenghuni", "rerun": "0"}, "8": {"status": "PASS", "message": "", "test_name": "test_8_InputKamarLayak", "rerun": "0"}, "9": {"status": "PASS", "message": "", "test_name": "test_9_InputKamarTidakLayak", "rerun": "0"}, "10": {"status": "PASS", "message": "", "test_name": "test_10_InputVentilasiLayak", "rerun": "0"}, "11": {"status": "PASS", "message": "", "test_name": "test_11_InputVentilasiTidakLayak", "rerun": "0"}, "12": {"status": "PASS", "message": "", "test_name": "test_12_InputPencahayaanLayak", "rerun": "0"}, "13": {"status": "PASS", "message": "", "test_name": "test_13_InputPencahayaanLayak", "rerun": "0"}, "14": {"status": "PASS", "message": "", "test_name": "test_14_InputKamarMandiLayak", "rerun": "0"}, "15": {"status": "PASS", "message": "", "test_name": "test_15_InputKamarMandiTidakLayal", "rerun": "0"}, "16": {"status": "PASS", "message": "", "test_name": "test_16_InputWcLayak", "rerun": "0"}, "17": {"status": "PASS", "message": "", "test_name": "test_17_InpuWcTidakLayak", "rerun": "0"}, "18": {"status": "FAIL", "message": "           TypeError: object of type 'NoneType' has no len()\n       assert False\n", "test_name": "test_18_InputAirLayak", "rerun": "0"}, "19": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x1068f3370>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=54164): Max retries exceeded with url: /session/648048ff836db51312b2515a3c1a7a3e/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1068f3370>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_19_InputAirLayak", "rerun": "0"}, "20": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x106c672e0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=54164): Max retries exceeded with url: /session/648048ff836db51312b2515a3c1a7a3e/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106c672e0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_20_InputTempatTidurLayak", "rerun": "0"}, "21": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x106cb1370>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=54164): Max retries exceeded with url: /session/648048ff836db51312b2515a3c1a7a3e/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106cb1370>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_21_InputTempatTidurTidakLayak", "rerun": "0"}, "22": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x106cebd60>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=54164): Max retries exceeded with url: /session/648048ff836db51312b2515a3c1a7a3e/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106cebd60>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_22_kasurLayak", "rerun": "0"}, "23": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x106880b50>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=54164): Max retries exceeded with url: /session/648048ff836db51312b2515a3c1a7a3e/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106880b50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_23_KasurTidakLayak", "rerun": "0"}, "24": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x106dd5040>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=54164): Max retries exceeded with url: /session/648048ff836db51312b2515a3c1a7a3e/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106dd5040>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_26_exit", "rerun": "0"}}, "suite_name": "4LaporanBulanan/4.Laporan6F/Fungsional/test_Laporan6F.py"}}}, "date": "April 12, 2023", "start_time": 1681270521.0131168, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "18", "fail": "7", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "25"}