{"content": {"suites": {"0": {"status": {"total_pass": 7, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 3, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_1_SetupOs", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_2_Login", "rerun": "0"}, "2": {"status": "PASS", "message": "", "test_name": "test_2_AksesMenu", "rerun": "0"}, "3": {"status": "PASS", "message": "", "test_name": "test_3_CreateButton", "rerun": "0"}, "4": {"status": "PASS", "message": "", "test_name": "test_3_SearchWBP", "rerun": "0"}, "5": {"status": "PASS", "message": "", "test_name": "test_4_PilihJenisGangguan", "rerun": "0"}, "6": {"status": "PASS", "message": "", "test_name": "test_5_ClickButtonDaftarkan", "rerun": "0"}, "7": {"status": "FAIL", "message": "   selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\"[id=\"jenisGangguan\"]\"}\n     (Session info: chrome=112.0.5615.49)\n   Stacktrace:\n   0   chromedriver                        0x0000000102a36ae8 chromedriver + 4958952\n   1   chromedriver                        0x0000000102a2e7b3 chromedriver + 4925363\n   2   chromedriver                        0x00000001025f01d6 chromedriver + 475606\n   3   chromedriver                        0x0000000102633a20 chromedriver + 752160\n   4   chromedriver                        0x0000000102633c81 chromedriver + 752769\n   5   chromedriver                        0x0000000102677f64 chromedriver + 1032036\n   6   chromedriver                        0x0000000102659c3d chromedriver + 908349\n   7   chromedriver                        0x000000010267525b chromedriver + 1020507\n   8   chromedriver                        0x00000001026599e3 chromedriver + 907747\n   9   chromedriver                        0x0000000102623aef chromedriver + 686831\n   10  chromedriver                        0x000000010262500e chromedriver + 692238\n   11  chromedriver                        0x00000001029f29ad chromedriver + 4680109\n   12  chromedriver                        0x00000001029f7c12 chromedriver + 4701202\n   13  chromedriver                        0x00000001029fe79f chromedriver + 4728735\n   14  chromedriver                        0x00000001029f8b7a chromedriver + 4705146\n   15  chromedriver                        0x00000001029cb27e chromedriver + 4518526\n   16  chromedriver                        0x0000000102a18908 chromedriver + 4835592\n   17  chromedriver                        0x0000000102a18a87 chromedriver + 4835975\n   18  chromedriver                        0x0000000102a2800f chromedriver + 4898831\n   19  libsystem_pthread.dylib             0x00007ff8173931d3 _pthread_start + 125\n   20  libsystem_pthread.dylib             0x00007ff81738ebd3 thread_start + 15\n       assert False\n", "test_name": "test_6_PilihJenisGangguan", "rerun": "0"}, "8": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x11c7350a0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=61352): Max retries exceeded with url: /session/136785cfb48d2bae6f446eed178df1cc/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11c7350a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_7_TglTerjadi", "rerun": "0"}, "9": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x11ca501c0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=61352): Max retries exceeded with url: /session/136785cfb48d2bae6f446eed178df1cc/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11ca501c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_29_exit", "rerun": "0"}}, "suite_name": "4LaporanBulanan/10.Laporan7D/Fungsional/test_Laporan7D.py"}}}, "date": "April 13, 2023", "start_time": 1681359424.9216058, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "7", "fail": "3", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "10"}